export * from './game';
// Re-export only selected API types to avoid name conflicts
export type {
  ApiResponse,
  TokenPayload,
  SSEEventType,
  SSEEvent,
  CreateRoomSchema,
  JoinRoomSchema,
  ReadySchema,
  ConfigUpdateSchema,
  SpeakSchema,
  VoteSchema,
  TiebreakSchema,
  KickPlayerSchema,
  TransferHostSchema,
  CustomTopicsSchema,
  ChatMessageSchema,
  CreateRoomRequest,
  JoinRoomRequest,
  ReadyRequest,
  ConfigUpdateRequest,
  SpeakRequest,
  VoteRequest,
  TiebreakRequest,
  KickPlayerRequest,
  TransferHostRequest,
  CustomTopicsRequest,
  ChatMessageRequest,
} from './api';
